### ISSUE TITLE
Support for "Go to previous error/warning"

### ISSUE THREAD

**Issue by daelmaak** [yy0931/go-to-next-error#6]
The title says it all, I'd like to add logic to go to the previous error/warning to round this useful plugin up. I can create a PR if you are interested.

**Comment by yy0931** [comment]
Feel free to create a PR and I'll merge it.

I've not created a contribution guide, but you can debug the extension by opening the repository with VSCode and pressing F5.

**Comment by daelmaak** [comment]
Cool. Would you have anything against converting to TypeScript in places? The jsdoc typings are quite messy.

**Comment by yy0931** [comment]
I don't have a strong opinion against that.
I didn't use TypeScript because the code was a small script of less than 100 lines and I felt an extra transpilation step wasn't worth it, but it might be better to convert to TypeScript if we plan to add more functionalities.
